/**
 * Midnight Network Type Definitions
 * Core data structures for privacy-preserving smart contract interactions
 */

export interface VaultData {
  vaultId: string
  owner: string
  currentPool: string
  tokenA: string
  tokenB: string
  depositAmount: number
  currentIL: number
  ilThreshold: number
  entryPrice: number
  status: 'healthy' | 'warning' | 'protected'
  createdAt: number
}

export interface RebalancingDecision {
  vaultId: string
  fromPool: string
  toPool: string
  currentIL: number
  expectedIL: number
  ilReduction: number
  confidence: number
  reason: string
  timestamp: number
}

export interface ZeroKnowledgeProof {
  // The actual proof (generated by Midnight private circuit)
  proof: string
  
  // Public signals that are verified on-chain (not secret)
  publicSignals: {
    // Vault identification (needed to link proof to vault)
    vaultIdHash: string
    
    // IL validation (prove IL calculation is correct)
    ilReductionValid: boolean
    currentILValue: number
    expectedILValue: number
    ilReductionAmount: number
    
    // Rebalancing validity (prove move is beneficial)
    rebalanceIsValid: boolean
    fromPoolHash: string
    toPoolHash: string
    
    // Confidence threshold (prove AI is confident)
    confidenceThreshold: number
    aiConfidenceValue: number
    confidenceCheckPassed: boolean
    
    // Timestamp for replay protection
    proofTimestamp: number
    proofNonce: string
  }
  
  // Metadata for frontend display
  metadata: {
    circuitName: string
    proofSize: number
    verificationTime: number // milliseconds
    constraints: number
  }
}

export interface MidnightTransaction {
  // Transaction metadata
  txId: string
  txHash?: string
  status: 'pending' | 'signed' | 'verified' | 'submitted' | 'confirmed' | 'failed'
  
  // The rebalancing details
  rebalancing: RebalancingDecision
  
  // The ZK proof ensuring validity
  proof: ZeroKnowledgeProof
  
  // User signature (proof of authorization)
  userSignature?: string
  
  // On-chain verification result
  onChainVerification?: {
    verificationStatus: 'verified' | 'failed'
    verificationTime: number
    blockNumber?: number
    blockHash?: string
    gasUsed?: number
  }
  
  // Timeline
  createdAt: number
  signedAt?: number
  submittedAt?: number
  confirmedAt?: number
  
  // Error handling
  error?: string
  errorDetails?: string
}

export interface MidnightContractCall {
  // Which contract method to call
  method: 'rebalance' | 'emergencyExit' | 'updateThreshold'
  
  // Input data (encrypted by Midnight)
  inputs: {
    vaultId: string
    fromPool: string
    toPool: string
    amount: number
    slippage: number
    minOutput: number
  }
  
  // The ZK proof
  proof: ZeroKnowledgeProof
  
  // Gas parameters
  gasLimit?: number
  gasPriceLovelace?: number
}

export interface ProofVerificationResult {
  isValid: boolean
  verificationTime: number
  constraints: number
  circuitChecks: {
    ilCalculationValid: boolean
    rebalanceBeneficial: boolean
    confidenceThresholdMet: boolean
    noReplayAttack: boolean
  }
  errorMessage?: string
}

export interface MidnightConfig {
  // Midnight Network API endpoint
  apiEndpoint: string
  
  // Contract addresses
  rebalancingContract: string
  verificationContract: string
  
  // Circuit parameters
  circuitName: string
  constraintCount: number
  
  // Timeout settings
  proofGenerationTimeout: number // milliseconds
  verificationTimeout: number // milliseconds
  
  // Proof caching
  enableProofCache: boolean
  cacheTTL: number // milliseconds
}

export interface RebalancingScenario {
  id: string
  name: string
  description: string
  vault: VaultData
  decision: RebalancingDecision
  expectedProof?: ZeroKnowledgeProof
  ilSavings: number
  timeToComplete: number // milliseconds
}
